id: opecha:P000531
initial_creation_type: ocr
source_metadata:
  id: bdr:W1AC327
  title: ཕྱག་རྒྱ་ཆེན་པོའི་སྒྲོས་འབུམ།
  volume:
    f9a4abc7229c463ea368ebbe86952e4a:
      image_group_id: I4PD4421
      title: Volume 1 of phyag rgya chen po'i sgros 'bum/
      volume_number: 1
      total_pages: 286
  author: ''
ebook_metadata:
  title: ཕྱག་རྒྱ་ཆེན་པོའི་སྒྲོས་འབུམ།
  author: ''
  sku: P000531
  cover: cover.jpg
  layers:
  - pagination
