id: P000531
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-16 15:44:52.136604
source_metadata:
  id: bdr:W1AC327
  title: ཕྱག་རྒྱ་ཆེན་པོའི་སྒྲོས་འབུམ།
  author: ''
  volumes:
    f9a4abc7229c463ea368ebbe86952e4a:
      image_group_id: I4PD4421
      title: Volume 1 of phyag rgya chen po'i sgros 'bum/
      volume_number: 1
      total_pages: 286
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
